CREATE TABLE IF NOT EXISTS links (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  url TEXT NOT NULL UNIQUE,
  short TEXT NOT NULL UNIQUE,
  secret TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  visits INTEGER NOT NULL DEFAULT 0
);